### ISSUE TITLE
undefined symbol: cublasLtGetStatusString, version libcublasLt.so.11

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [hcnoh/gail-pytorch#5]
When I run the train.py as your instruction, the following error occurred.

```
$ python3 train.py --env_name=BipedalWalker-v3
Traceback (most recent call last):
  File "/home/dl/GAIL/GAIL/lib/python3.8/site-packages/torch/__init__.py", line 172, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/dl/GAIL/GAIL/lib/python3.8/site-packages/torch/lib/../../nvidia/cublas/lib/libcublas.so.11: undefined symbol: cublasLtGetStatusString, version libcublasLt.so.11

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 6, in <module>
    import torch
  File "/home/dl/GAIL/GAIL/lib/python3.8/site-packages/torch/__init__.py", line 217, in <module>
    _load_global_deps()
  File "/home/dl/GAIL/GAIL/lib/python3.8/site-packages/torch/__init__.py", line 178, in _load_global_deps
    _preload_cuda_deps()
  File "/home/dl/GAIL/GAIL/lib/python3.8/site-packages/torch/__init__.py", line 158, in _preload_cuda_deps
    ctypes.CDLL(cublas_path)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/dl/GAIL/GAIL/lib/python3.8/site-packages/nvidia/cublas/lib/libcublas.so.11: undefined symbol: cublasLtGetStatusString, version libcublasLt.so.11
```
Please let me know how to fix it.

**Comment by hcnoh** [comment]
This seems to be a PyTorch issue. Please check the [link](https://stackoverflow.com/questions/74394695/how-does-one-fix-when-torch-cant-find-cuda-error-version-libcublaslt-so-11-no).

**Comment by Ishihara-Masabumi** [comment]
OK, thanks.
